# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty  

# Setup
title:            Aphasia Support Group of Rochester
tagline:          'An Aphasia focused support group serving the greater Rochester area.'
description:      'Supporting and empowering persons with Aphasia and their caregivers.'
url:              https://apasiasupportgroup.com
baseurl:          /

author:
  name:           'Apasia Support Group of Rochester'
  url:            https://apasiasupportgroup.com

paginate:         5
paginate_path:    "news/page:num/"

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/reustonium/asgor-web

gems:             ['jekyll-github-metadata']