# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty  

# Setup
title:            Aphasia Support Group of Rochester
tagline:          'An Apasia focused support group serving the greater Rochester area.'
description:      'Building connections and communication skils.'
url:              https://apasiasupportgroup.com
baseurl:          /

author:
  name:           'Apasia Support Group of Rochester'
  url:            https://apasiasupportgroup.com

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/reustonium/asgor-web

gems:             ['jekyll-github-metadata']